Repository woowacourse-teams/2025-moaon, pull requests merged in 2025-07, with the labels that each got.

#12 refactor: PR 설정 자동화 워크플로우 수정
  .github/workflows/auto-review-assign-pr.yml
Labels: FE

#6 chore: 도커 환경 구축
  backend/.gitignore
  backend/Dockerfile
  backend/docker-compose.yml
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application.yml
Labels: BE

#27 chore: codebuild 명령어 파일 추가
  frontend/buildspec.yml
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/webpack.config.js
Labels: FE

#28 Deploy: FE 프로덕션 배포 테스트
  .github/workflows/auto-assign-issue.yml
  .github/workflows/auto-review-assign-pr.yml
  .github/workflows/be-dev-cd.yml
  .github/workflows/be-dev-ci.yml
  .github/workflows/fe-build-test.yml
  .github/workflows/fe-dev-deploy.yml
  backend/.gitattributes
  backend/.gitignore
  backend/Dockerfile
  backend/build.gradle
  backend/compose.yaml
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/moaon/backend/BackendApplication.java
  backend/src/main/java/moaon/backend/category/domain/Category.java
  backend/src/main/java/moaon/backend/global/domain/BaseTimeEntity.java
  backend/src/main/java/moaon/backend/group/domain/Organization.java
  backend/src/main/java/moaon/backend/love/domain/Love.java
  backend/src/main/java/moaon/backend/platform/domain/Platform.java
  backend/src/main/java/moaon/backend/project/domain/Images.java
  backend/src/main/java/moaon/backend/project/domain/Project.java
  backend/src/main/java/moaon/backend/techStack/domain/TechStack.java
  backend/src/main/java/moaon/backend/user/domain/Member.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/moaon/backend/BackendApplicationTests.java
  backend/src/test/resources/application.yml
  frontend/.gitignore
  frontend/.vscode/extensions.json
  frontend/.vscode/settings.json
  frontend/biome.json
  frontend/build.sh
  frontend/buildspec.yml
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/main.tsx
  frontend/src/styles/reset.styled.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
Labels: FE

#33 fix: styled 문법 포맷 안되는 문제 해결
  frontend/.vscode/extensions.json
  frontend/.vscode/settings.json
Labels: FE

#31 feat: 전체 프로젝트 조회 및 검색 API 구현
  backend/build.gradle
  backend/src/main/java/moaon/backend/global/config/QueryDslConfig.java
  backend/src/main/java/moaon/backend/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/moaon/backend/global/exception/custom/ErrorCode.java
  backend/src/main/java/moaon/backend/project/controller/ProjectController.java
  backend/src/main/java/moaon/backend/project/domain/Project.java
  backend/src/main/java/moaon/backend/project/dto/ProjectQueryCondition.java
  backend/src/main/java/moaon/backend/project/dto/ProjectSummaryResponse.java
  backend/src/main/java/moaon/backend/project/repository/CustomizedProjectRepository.java
  backend/src/main/java/moaon/backend/project/repository/CustomizedProjectRepositoryImpl.java
  backend/src/main/java/moaon/backend/project/repository/ProjectRepository.java
  backend/src/main/java/moaon/backend/project/service/ProjectService.java
  backend/src/test/java/moaon/backend/api/project/ProjectApiTest.java
  backend/src/test/java/moaon/backend/fixture/Fixture.java
  backend/src/test/java/moaon/backend/fixture/RepositoryTestHelper.java
  backend/src/test/java/moaon/backend/project/repository/CustomizedProjectRepositoryImplTest.java
Labels: BE

#35 feat: 캐러셀 컴포넌트 구현
  frontend/src/App.tsx
  frontend/src/pages/detail/DetailPage.tsx
  frontend/src/pages/detail/components/carousel/Carousel.styled.ts
  frontend/src/pages/detail/components/carousel/Carousel.tsx
  frontend/src/pages/detail/components/carousel/hooks/useArrowKey.ts
  frontend/src/pages/detail/components/carousel/hooks/useSlide.ts
  frontend/src/shared/components/Layout/GlobalLayout.styled.ts
  frontend/src/shared/components/Layout/GlobalLayout.tsx
  frontend/src/styles/reset.styled.ts
Labels: FE

#39 feat(FE): 상세 페이지 TitleSection, OverviewSection 부분 구현
  frontend/src/assets/icons/heart-outline.svg
  frontend/src/assets/icons/heart.svg
  frontend/src/assets/icons/home.svg
  frontend/src/assets/icons/logo-github.svg
  frontend/src/pages/detail/DetailPage.tsx
  frontend/src/pages/detail/components/OverviewSection/OverviewSection.styled.ts
  frontend/src/pages/detail/components/OverviewSection/OverviewSection.tsx
  frontend/src/pages/detail/components/TitleSection/TitleSection.styled.ts
  frontend/src/pages/detail/components/TitleSection/TitleSection.tsx
  frontend/src/svg.d.ts
  frontend/webpack.config.js
Labels: FE

#37 feat(BE): 프로젝트 정렬 API 구현
  backend/src/main/java/moaon/backend/global/domain/BaseTimeEntity.java
  backend/src/main/java/moaon/backend/love/domain/Love.java
  backend/src/main/java/moaon/backend/love/repository/LoveRepository.java
  backend/src/main/java/moaon/backend/project/controller/ProjectController.java
  backend/src/main/java/moaon/backend/project/domain/Project.java
  backend/src/main/java/moaon/backend/project/domain/SortBy.java
  backend/src/main/java/moaon/backend/project/dto/ProjectDetailResponse.java
  backend/src/main/java/moaon/backend/project/dto/ProjectQueryCondition.java
  backend/src/main/java/moaon/backend/project/dto/ProjectSummaryResponse.java
  backend/src/main/java/moaon/backend/project/repository/CustomizedProjectRepositoryImpl.java
  backend/src/main/java/moaon/backend/project/service/ProjectService.java
  backend/src/test/java/moaon/backend/api/project/ProjectApiTest.java
  backend/src/test/java/moaon/backend/fixture/RepositoryTestHelper.java
  backend/src/test/java/moaon/backend/project/domain/SortByTest.java
  backend/src/test/java/moaon/backend/project/repository/CustomizedProjectRepositoryImplTest.java
Labels: BE

#42 feat(FE): 탐색 페이지 구현
  frontend/.vscode/settings.json
  frontend/src/App.tsx
  frontend/src/assets/icons/fill-heart.svg
  frontend/src/assets/icons/logo.svg
  frontend/src/assets/icons/search.svg
  frontend/src/assets/icons/view.svg
  frontend/src/pages/list/CardList/Card/ActivityBox/ActivityBox.styled.ts
  frontend/src/pages/list/CardList/Card/ActivityBox/ActivityBox.tsx
  frontend/src/pages/list/CardList/Card/Card.styled.ts
  frontend/src/pages/list/CardList/Card/Card.tsx
  frontend/src/pages/list/CardList/Card/PlatformList/Platform/Platform.styled.tsx
  frontend/src/pages/list/CardList/Card/PlatformList/Platform/Platform.tsx
  frontend/src/pages/list/CardList/Card/PlatformList/PlatformList.styled.ts
  frontend/src/pages/list/CardList/Card/PlatformList/PlatformList.tsx
  frontend/src/pages/list/CardList/Card/TechStackList/TechStack/TechStack.styled.ts
  frontend/src/pages/list/CardList/Card/TechStackList/TechStack/TechStack.tsx
  frontend/src/pages/list/CardList/Card/TechStackList/TechStackList.styled.ts
  frontend/src/pages/list/CardList/Card/TechStackList/TechStackList.tsx
  frontend/src/pages/list/CardList/CardList.styled.ts
  frontend/src/pages/list/CardList/CardList.tsx
  frontend/src/pages/list/Filter/Filter.styled.ts
  frontend/src/pages/list/Filter/Filter.tsx
  frontend/src/pages/list/Filter/FilterBox/FilterBox.styled.ts
  frontend/src/pages/list/Filter/FilterBox/FilterBox.tsx
  frontend/src/pages/list/Filter/FilterBox/FilterList/FilterList.styled.ts
  frontend/src/pages/list/Filter/FilterBox/FilterList/FilterList.tsx
  frontend/src/pages/list/ListPage.tsx
  frontend/src/shared/components/ArrowIcon/ArrowIcon.tsx
  frontend/src/shared/components/Header/Header.styled.ts
  frontend/src/shared/components/Header/Header.tsx
  frontend/src/shared/components/Header/NavBar/NavBar.styled.ts
  frontend/src/shared/components/Header/NavBar/NavBar.tsx
  frontend/src/shared/components/Header/RegisterProjectButton/RegisterProjectButton.styled.ts
  frontend/src/shared/components/Header/RegisterProjectButton/RegisterProjectButton.tsx
  frontend/src/shared/components/SearchBar/SearchBar.styled.ts
  frontend/src/shared/components/SearchBar/SearchBar.tsx
  frontend/src/shared/hooks/useOutsideClick.ts
  frontend/src/shared/hooks/useSearchParams.ts
  frontend/src/styles/global.styled.ts
  frontend/src/svg.d.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
Labels: FE

#44 chore: PR Preview 설정 추가
  .github/workflows/fe-pr-preview.yml
  frontend/.gitignore
  frontend/vercel.json
Labels: FE

#53 docs(BE): READEM.md 내용 추가
  README.md
Labels: BE

#59 chore(BE, FE): coderabbit ai 설정
  .coderabbit.yaml
  docs/be-code-convention.md
  docs/fe-code-convention.md
Labels: FE, BE

#60 feat(FE): 탐색 페이지 API 연동
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/apis/HttpClient.ts
  frontend/src/apis/projects/getProjects.ts
  frontend/src/apis/projects/project.queries.ts
  frontend/src/apis/projects/projects.type.ts
  frontend/src/assets/icons/reset.svg
  frontend/src/assets/images/default-thumbnail.webp
  frontend/src/domains/filter/category.ts
  frontend/src/domains/filter/iconBadge.ts
  frontend/src/domains/filter/organization.ts
  frontend/src/domains/filter/platform.ts
  frontend/src/domains/filter/techStack.ts
  frontend/src/image.d.ts
  frontend/src/main.tsx
  frontend/src/pages/detail/components/PlatformSection/PlatformSection.tsx
  frontend/src/pages/detail/components/TechStacksSection/TechStacksSection.tsx
  frontend/src/pages/list/CardList/Card/ActivityBox/ActivityBox.styled.ts
  frontend/src/pages/list/CardList/Card/Card.styled.ts
  frontend/src/pages/list/CardList/Card/Card.tsx
  frontend/src/pages/list/CardList/Card/PlatformList/PlatformList.tsx
  frontend/src/pages/list/CardList/Card/TechStackList/TechStack/TechStack.tsx
  frontend/src/pages/list/CardList/Card/TechStackList/TechStackList.tsx
  frontend/src/pages/list/CardList/CardList.tsx
  frontend/src/pages/list/Filter/Filter.tsx
  frontend/src/pages/list/Filter/FilterBox/FilterBox.tsx
  frontend/src/pages/list/Filter/FilterBox/FilterList/FilterList.tsx
  frontend/src/pages/list/FilterContainer/FilterContainer.styled.ts
  frontend/src/pages/list/FilterContainer/FilterContainer.tsx
  frontend/src/pages/list/FilterContainer/FilterTrigger/FilterBox/FilterBox.styled.ts
  frontend/src/pages/list/FilterContainer/FilterTrigger/FilterBox/FilterBox.tsx
  frontend/src/pages/list/FilterContainer/FilterTrigger/FilterBox/FilterList/FilterButton/FilterButton.styled.ts
  frontend/src/pages/list/FilterContainer/FilterTrigger/FilterBox/FilterList/FilterButton/FilterButton.tsx
  frontend/src/pages/list/FilterContainer/FilterTrigger/FilterBox/FilterList/FilterList.styled.ts
  frontend/src/pages/list/FilterContainer/FilterTrigger/FilterBox/FilterList/FilterList.tsx
  frontend/src/pages/list/FilterContainer/FilterTrigger/FilterTrigger.styled.ts
  frontend/src/pages/list/FilterContainer/FilterTrigger/FilterTrigger.tsx
  frontend/src/pages/list/ListPage.styled.ts
  frontend/src/pages/list/ListPage.tsx
  frontend/src/pages/list/SortList/SortItem/SortItem.styled.ts
  frontend/src/pages/list/SortList/SortItem/SortItem.tsx
  frontend/src/pages/list/SortList/SortList.styled.ts
  frontend/src/pages/list/SortList/SortList.tsx
  frontend/src/pages/list/hooks/useProjectList.ts
  frontend/src/shared/components/IconBadgeList/IconBadge/IconBadge.styled.ts
  frontend/src/shared/components/IconBadgeList/IconBadge/IconBadge.tsx
  frontend/src/shared/components/IconBadgeList/IconBadgeList.tsx
  frontend/src/shared/components/IconBadgeList/constants/iconMap.ts
  frontend/src/shared/components/Layout/GlobalLayout.styled.ts
  frontend/src/shared/components/SearchBar/SearchBar.styled.ts
  frontend/src/shared/components/SearchBar/SearchBar.tsx
  frontend/src/shared/components/Separated/Separated.tsx
  frontend/src/shared/hooks/useSearchParams.ts
  frontend/src/styles/reset.styled.ts
  frontend/src/svg.d.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
Labels: FE

#55 chore(BE): querydsl 버전 및 source 디렉토리 변경
  backend/build.gradle
Labels: BE

#63 fix: 레거시 filter 폴더 및 코드 제거
  frontend/src/pages/detail/components/TitleSection/TitleSection.tsx
  frontend/src/pages/list/CardList/CardList.tsx
  frontend/src/pages/list/CardList/hooks/useProjectList.ts
  frontend/src/pages/list/FilterContainer/Filter/Filter.styled.ts
  frontend/src/pages/list/FilterContainer/Filter/Filter.tsx
  frontend/src/pages/list/FilterContainer/Filter/FilterBox/FilterBox.styled.ts
  frontend/src/pages/list/FilterContainer/Filter/FilterBox/FilterBox.tsx
  frontend/src/pages/list/FilterContainer/Filter/FilterBox/FilterList/FilterList.styled.ts
  frontend/src/pages/list/FilterContainer/Filter/FilterBox/FilterList/FilterList.tsx
Labels: FE

#66 chore(FE): 기술스택, 플랫폼 아이콘 S3 경로 적용
  frontend/src/domains/filter/platform.ts
  frontend/src/domains/filter/techStack.ts
Labels: FE

#74 fix(BE): CORS 에러 해결
  backend/src/main/java/moaon/backend/global/config/WebConfig.java
Labels: BE

#83 feat(FE): UT를 위한 상세 정보 Mock Data 추가
  frontend/src/pages/detail/DetailPage.tsx
  frontend/src/pages/detail/components/Post/Post.styled.ts
  frontend/src/pages/detail/components/Post/Post.tsx
  frontend/src/shared/components/Layout/GlobalLayout.styled.ts
Labels: FE

#86 fix(FE): 슬라이드가 하나일 때 이전/다음 버튼 숨기기
  frontend/src/pages/detail/components/Carousel/Carousel.tsx
Labels: FE

#87 feat: 선택된 필터 리스트 보여주기
  frontend/src/assets/icons/close.svg
  frontend/src/pages/list/CardList/CardList.styled.ts
  frontend/src/pages/list/FilterContainer/FilterContainer.tsx
  frontend/src/pages/list/FilterContainer/FilterTrigger/FilterBox/FilterBox.tsx
  frontend/src/pages/list/ListPage.styled.ts
  frontend/src/pages/list/ListPage.tsx
  frontend/src/pages/list/hooks/useFilterParams.ts
  frontend/src/shared/components/Header/Header.tsx
  frontend/webpack.config.js
Labels: FE

#101 refactor(FE): 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/FEATURE.md
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/REFACTOR.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: FE

#105 fix(FE): 이슈 템플릿 변경
  .github/ISSUE_TEMPLATE/TASK_TEMPLATE.md
Labels: FE
